server: "hub-cloud.browserstack.com"
user: "vegardwright1"
key: "9rq65RGLe4vFw7qqUwh7"

common_caps:
  "build": "capybara-browserstack"
  "browserstack.debug": true
  "acceptSslCerts": true


browser_caps:
  -
    "browser": "chrome"
    "browserstack.local": true
